# Generated by Django 3.2.3 on 2021-05-16 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.misiksuser')),
            ],
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('modify_date', models.DateField(auto_now=True)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.misiksuser'),
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('type', models.IntegerField(choices=[(1, 'Бизнес'), (2, 'Функциональные')])),
                ('description', models.CharField(max_length=5000)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('modify_date', models.DateField(auto_now=True)),
                ('status', models.IntegerField(choices=[(1, 'new'), (2, 'inProgress'), (3, 'correction'), (4, 'done'), (5, 'atApproval'), (6, 'approved')], default=1)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.misiksuser')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.requirement')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project')),
                ('release', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.release')),
            ],
        ),
        migrations.AddField(
            model_name='release',
            name='specification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.specification'),
        ),
    ]
