# Generated by Django 3.2.3 on 2021-05-16 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210516_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='specification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='release', to='api.specification'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.requirement'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='release',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirements', to='api.release'),
        ),
    ]
