# Generated by Django 3.2.3 on 2021-05-16 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210516_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='api.project'),
        ),
    ]
