# Generated by Django 3.2.3 on 2021-05-22 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_project_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='state',
            field=models.CharField(choices=[('new', 'New'), ('inProgress', 'In Progress'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='new', max_length=10),
        ),
    ]
