# Generated by Django 3.2.3 on 2021-05-22 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_project_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('inProgress', 'In Progress'), ('correction', 'Correction'), ('done', 'Done'), ('atApproval', 'At Approval'), ('approved', 'Approved')], default='new', max_length=10),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='type',
            field=models.CharField(choices=[('Бизнес', 'Business'), ('Функциональные', 'Functional')], max_length=14),
        ),
    ]
