# Generated by Django 3.2.3 on 2021-05-23 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210522_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='specification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirements', to='api.specification'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='release',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.release'),
        ),
    ]
